vich_uploader:
    db_driver: orm

    mappings:
        news:
            uri_prefix: '%news_upload_path%'
            upload_destination: '%kernel.project_dir%/public/%news_upload_path%'
        partner:
            uri_prefix: '%partner_upload_path%'
            upload_destination: '%kernel.project_dir%/public/%partner_upload_path%'

